### ISSUE TITLE
CustomerSignUpAvtivity

### ISSUE THREAD

**Issue by jaldesa** [sakshamsachdeva/MedRescue#1]
CustomerSignUpAvtivity class not available as included in manifest file. Also no such class in source.

Kindly reply sir. 

Thank you.

Adan.

**Comment by sakshamsachdeva** [comment]
The said class is available at the link provided below. It is available since the day I created this repository.

https://github.com/sakshamsachdeva/MedRescue/blob/master/app/src/main/java/sachdeva/saksham/medrescue/CustomerSignup.java
